[tool.ruff]
line-length = 100
target-version = "py311"
fix = true
extend-exclude = ["__MACOSX", "._*", "ISA_synthesized/**"]

[tool.ruff.lint]
select = ["E","F","W","I","UP"]
ignore = ["E203","E501"]

[tool.mypy]
python_version = "3.11"
strict = false
warn_unused_ignores = true
warn_redundant_casts = true
no_implicit_optional = true
namespace_packages = true
mypy_path = ["ISA_SuperApp/src"]

[[tool.mypy.overrides]]
module = [
  "fastjsonschema",
  "sentence_transformers",
  "opentelemetry.*",
  "yaml",
  "langchain",
]
ignore_missing_imports = true
