site_name: ISA_C Documentation
theme:
  name: material
  features:
    - navigation.tabs
    - search.highlight
    - content.code.copy

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true

nav:
  - Home: README_en.md
  - Architecture:
    - Diagram: architecture/diagram.mmd
    - ADRs: architecture/decisions/
  - Tutorials:
    - Getting Started: tutorials/getting-started.md
