version: '3.9'
services:
  api:
    build: .
    ports:
      - "8787:8787"
    depends_on:
      - postgres
      - minio
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8787/metrics')"]
      interval: 30s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: isa
      POSTGRES_USER: isa
      POSTGRES_PASSWORD: isa
      POSTGRES_HOST: postgres
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_HOST: minio
    restart: unless-stopped

  postgres:
    image: ankane/pgvector:pg16
    environment:
      POSTGRES_DB: isa
      POSTGRES_USER: isa
      POSTGRES_PASSWORD: isa
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data:
