openapi: 3.0.3
info:
  title: ISA ESG Data API
  version: 0.1.0
paths:
  /datasets:
    get:
      summary: List datasets
      responses: { "200": { "description": "OK" } }
  /records:
    get:
      summary: List records
      responses: { "200": { "description": "OK" } }
