version: '3.9'
services:
  postgres:
    image: ankane/pgvector:pg16
    environment:
      POSTGRES_DB: isa
      POSTGRES_USER: isa
      POSTGRES_PASSWORD: isa
    ports: ["5433:5432"]
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports: ["9000:9000","9001:9001"]
