name: Determinism Matrix

on:
  workflow_dispatch:

jobs:
  snapshot:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.11", "3.12"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r ISA_SuperApp/requirements.txt -r ISA_SuperApp/requirements-dev.txt
      - name: Run determinism snapshot test
        run: |
          cd ISA_SuperApp && pytest -q tests/unit/test_snapshot_canonical_sample.py
