name: Auto Update Docs (PR)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  docs-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run auto doc update
        run: |
          python scripts/auto_doc_update.py
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(docs): auto-update Last updated timestamps"
          title: "chore(docs): auto-update Last updated timestamps"
          body: "Automated documentation refresh run."
          branch: docs/auto-update
          labels: documentation
